output_directory: results
email: you@example.com
min_ref_count_for_summary: 60
min_ref_counts_per_profession:
  'basketball player': 100
  'economist': 150
min_ref_counts_per_sole_profession:
  'architect': 80


